### ISSUE TITLE
Ranges and Offsets - com_error / exception

### ISSUE THREAD

**Issue by Kebap** [pythonexcels/examples#1]
When I try running [your test script](https://github.com/pythonexcels/examples/blob/master/ranges_and_offsets.py), I get the following error traceback. It relates to the line with combined ranges ("A6:B7,A9:B10")

```
Traceback (most recent call last):
  File "<string>", line 245, in run_nodebug
  File "<module1>", line 7, in <module>
  File "C:\Users\kebap\AppData\Local\Temp\gen_py\2.7\00020813-0000-0000-C000-000000000046x0x1x7\Sheets.py", line 113, in __call__
    ret = self._oleobj_.InvokeTypes(0, LCID, 2, (9, 0), ((12, 1),),Index
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, None, None, None, 0, -2147352565), None)
```

**Comment by sriharshabulusu** [comment]
I tried running the scripts and i am facing the same error and find the solution ,so the solution will be 
ranges ("A6:B7;A9:B10") **(coma"," should be replaced by semi colon";")**

**Comment by pythonexcels** [comment]
I've tried this on Excel 2007 and Excel 2015 and don't see this error. Nevertheless, I've just checked in a change. This statement:

    ws.Range("A6:B7,A9:B10").Value = "A6:B7,A9:B10"

is changed to this:

    try:
        ws.Range("A6:B7,A9:B10").Value = "A6:B7,A9:B10"
    except:
        ws.Range("A6:B7;A9:B10").Value = "A6:B7,A9:B10"
